apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ocp-datalake-demo
  namespace: ocp-datalake
  labels:
    app.kubernetes.io/name: ocp-datalake-demo
    app.kubernetes.io/part-of: ocp-datalake
    opendatahub.io/dashboard: "true"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: gp3-csi
