apiVersion: v1
kind: ServiceAccount
metadata:
  name: ocp-datalake-demo
  namespace: ocp-datalake
  labels:
    app.kubernetes.io/name: ocp-datalake-demo
    app.kubernetes.io/part-of: ocp-datalake
    opendatahub.io/dashboard: "true"
