apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: redhat-ods-applications
  labels:
    app: postgres
    purpose: poc
    app.kubernetes.io/part-of: ocp-datalake-maas
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
