apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  namespace: redhat-ods-applications
  labels:
    app: postgres
    app.kubernetes.io/part-of: ocp-datalake-maas
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
