apiVersion: v1
kind: Namespace
metadata:
  name: ocp-datalake
  labels:
    app.kubernetes.io/part-of: ocp-datalake
    argocd.argoproj.io/managed-by: openshift-gitops
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
