apiVersion: v1
kind: LimitRange
metadata:
  name: ocp-datalake-limits
  namespace: ocp-datalake
  labels:
    app.kubernetes.io/part-of: ocp-datalake
spec:
  limits:
    - type: Container
      default:
        cpu: 200m
        memory: 256Mi
      defaultRequest:
        cpu: 50m
        memory: 64Mi
      max:
        cpu: "2"
        memory: 2Gi
    - type: PersistentVolumeClaim
      max:
        storage: 1Gi
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: ocp-datalake-quota
  namespace: ocp-datalake
  labels:
    app.kubernetes.io/part-of: ocp-datalake
spec:
  hard:
    pods: "24"
    requests.cpu: "3"
    requests.memory: 4Gi
    limits.cpu: "10"
    limits.memory: 12Gi
    persistentvolumeclaims: "3"
    requests.storage: 3Gi
