apiVersion: v1
kind: LimitRange
metadata:
  name: ocp-datalake-limits
  namespace: ocp-datalake
  labels:
    app.kubernetes.io/part-of: ocp-datalake
spec:
  limits:
    - type: Container
      default:
        cpu: 200m
        memory: 256Mi
      defaultRequest:
        cpu: 50m
        memory: 64Mi
      max:
        cpu: "4"
        memory: 8Gi
    - type: PersistentVolumeClaim
      max:
        storage: 2Gi
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: ocp-datalake-quota
  namespace: ocp-datalake
  labels:
    app.kubernetes.io/part-of: ocp-datalake
spec:
  hard:
    pods: "24"
    requests.cpu: "6"
    requests.memory: 10Gi
    limits.cpu: "16"
    limits.memory: 20Gi
    persistentvolumeclaims: "5"
    requests.storage: 5Gi
