apiVersion: v1
kind: LimitRange
metadata:
  name: ocp-datalake-limits
  namespace: ocp-datalake
  labels:
    app.kubernetes.io/part-of: ocp-datalake
spec:
  limits:
    - type: Container
      default:
        cpu: 200m
        memory: 256Mi
      defaultRequest:
        cpu: 50m
        memory: 64Mi
      max:
        cpu: "1"
        memory: 1Gi
    - type: PersistentVolumeClaim
      max:
        storage: 1Gi
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: ocp-datalake-quota
  namespace: ocp-datalake
  labels:
    app.kubernetes.io/part-of: ocp-datalake
spec:
  hard:
    pods: "12"
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "4"
    limits.memory: 4Gi
    persistentvolumeclaims: "1"
    requests.storage: 1Gi
