# OpenShift Pipelines creates ServiceAccount "pipeline" in the namespace.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: inference
  namespace: ocp-datalake
  labels:
    app.kubernetes.io/part-of: ocp-datalake
  annotations:
    serviceaccounts.openshift.io/oauth-redirectreference.primary: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"inference"}}'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: databricks-puller
  namespace: ocp-datalake
  labels:
    app.kubernetes.io/part-of: ocp-datalake
rules:
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
  - apiGroups: ["apps"]
    resources: ["deployments", "replicasets"]
    verbs: ["get", "list", "watch", "patch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["serving.kserve.io"]
    resources: ["inferenceservices"]
    verbs: ["get", "list", "watch", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: databricks-puller
  namespace: ocp-datalake
  labels:
    app.kubernetes.io/part-of: ocp-datalake
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: databricks-puller
subjects:
  - kind: ServiceAccount
    name: pipeline
    namespace: ocp-datalake
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: inference-oauth
  namespace: ocp-datalake
  labels:
    app.kubernetes.io/part-of: ocp-datalake
rules:
  - apiGroups: [""]
    resources: ["services"]
    resourceNames: ["inference"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: inference-oauth
  namespace: ocp-datalake
  labels:
    app.kubernetes.io/part-of: ocp-datalake
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: inference-oauth
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: system:authenticated
