apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ocp-datalake-inference-auth-delegator
  labels:
    app.kubernetes.io/part-of: ocp-datalake
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - kind: ServiceAccount
    name: inference
    namespace: ocp-datalake
