apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: databricks-ml-registry
  namespace: ocp-datalake
  labels:
    app.kubernetes.io/part-of: ocp-datalake
    app.kubernetes.io/name: databricks-ml-registry
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: gp3-csi
