apiVersion: v1
kind: ConfigMap
metadata:
  name: ml-runtime
  namespace: ocp-datalake
  labels:
    app.kubernetes.io/part-of: ocp-datalake
data:
  MODEL_PATH: /opt/app-root/src/model.json
  BIND: 0.0.0.0
  PORT: "8080"
  MODEL_KEY: models/churn-score/1/model.json
---
apiVersion: v1
kind: Secret
metadata:
  name: oauth-proxy
  namespace: ocp-datalake
  labels:
    app.kubernetes.io/part-of: ocp-datalake
type: Opaque
stringData:
  cookie-secret: qNaMcafOpOx5JJLV2zLSWA==
