apiVersion: datasciencepipelinesapplications.opendatahub.io/v1
kind: DataSciencePipelinesApplication
metadata:
  name: dspa
  namespace: ocp-datalake
  labels:
    app.kubernetes.io/part-of: ocp-datalake
spec:
  dspVersion: v2
  apiServer:
    deploy: true
    enableOauth: true
    enableSamplePipeline: false
    pipelineStore: kubernetes
    cacheEnabled: false
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 1Gi
  database:
    mariaDB:
      deploy: true
      pvcSize: 1Gi
      storageClassName: gp3-csi
      resources:
        requests:
          cpu: 50m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 512Mi
  objectStorage:
    minio:
      deploy: true
      image: quay.io/opendatahub/minio:RELEASE.2019-08-14T20-37-41Z-license-compliance
      pvcSize: 1Gi
      storageClassName: gp3-csi
      resources:
        requests:
          cpu: 50m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 512Mi
