apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: openshift-integration-operator
  namespace: openshift-integration
  labels:
    app.kubernetes.io/part-of: ocp-datalake
spec:
  channel: candidate-v0
  installPlanApproval: Automatic
  name: openshift-integration-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
