apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - kuadrant-namespace.yaml
  - authorino-service.yaml
  - kuadrant.yaml
  - gatewayclass.yaml
  - gateway-resources.yaml
  - authorino.yaml
  - gateway.yaml
  - route.yaml

