apiVersion: v1
kind: Namespace
metadata:
  name: stackable-operators
  labels:
    app.kubernetes.io/part-of: ocp-datalake
    app.kubernetes.io/name: stackable-operators
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: stackable-operators
  namespace: stackable-operators
  labels:
    app.kubernetes.io/part-of: ocp-datalake
spec: {}
---
# Commons / Secret / Listener are required by every Stackable operator.
# https://docs.stackable.tech/home/stable/spark-k8s/getting_started/installation/
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: stackable-commons-operator
  namespace: stackable-operators
  labels:
    app.kubernetes.io/part-of: ocp-datalake
spec:
  channel: stable
  installPlanApproval: Automatic
  name: stackable-commons-operator
  source: certified-operators
  sourceNamespace: openshift-marketplace
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: stackable-secret-operator
  namespace: stackable-operators
  labels:
    app.kubernetes.io/part-of: ocp-datalake
spec:
  channel: stable
  installPlanApproval: Automatic
  name: stackable-secret-operator
  source: certified-operators
  sourceNamespace: openshift-marketplace
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: stackable-listener-operator
  namespace: stackable-operators
  labels:
    app.kubernetes.io/part-of: ocp-datalake
spec:
  channel: stable
  installPlanApproval: Automatic
  name: stackable-listener-operator
  source: certified-operators
  sourceNamespace: openshift-marketplace
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: stackable-spark-operator
  namespace: stackable-operators
  labels:
    app.kubernetes.io/part-of: ocp-datalake
spec:
  channel: stable
  installPlanApproval: Automatic
  name: stackable-spark-operator
  source: certified-operators
  sourceNamespace: openshift-marketplace
