apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ocp-datalake
  namespace: openshift-gitops
  labels:
    app.kubernetes.io/part-of: ocp-datalake
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://github.com/maximilianoPizarro/ocp-datalake.git
    targetRevision: main
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: ocp-datalake
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
  ignoreDifferences:
    - group: tekton.dev
      kind: Task
      jsonPointers:
        - /status
    - group: serving.kserve.io
      kind: InferenceService
      jsonPointers:
        - /status
    - group: datasciencepipelinesapplications.opendatahub.io
      kind: DataSciencePipelinesApplication
      jsonPointers:
        - /status
