apiVersion: v1
kind: Namespace
metadata:
  name: llm
  annotations:
    openshift.io/display-name: MaaS LLM projects
  labels:
    app.kubernetes.io/part-of: ocp-datalake-maas
    opendatahub.io/dashboard: "true"
    opendatahub.io/generated-namespace: "true"
    maas.opendatahub.io/gateway-access: "true"
